config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'application#index', as: :home
  get 'facebook' => 'facebook#index'
  get 'wishlist' => 'application#wishlist'
  get 'my-wishlist/:id' => 'application#mywishlist', as: :mywishlist
  get 'thanks' => 'application#thanks'
  get 'catalog(/:slug)' => 'application#catalog', as: :catalog
  get 'addproduct/:slug' => 'application#addproduct', as: :addproduct
  get 'removeproduct/:slug' => 'application#removeproduct', as: :removeproduct
  post 'addwishlist' => 'application#addwishlist', as: :addwishlist
  get 'addfriend' => 'application#addfriend'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  #belongs_to :user
  has_many :wishlist
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :wishlist

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend

  has_many :wishlist_detail, dependent: :destroy

  accepts_nested_attributes_for :wishlist_detail

end

app/models/wishlist_detail.rb
class WishlistDetail < ActiveRecord::Base
  belongs_to :wishlist
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end

  def catalog

    user_id = session[:user_id]
    if user_id.nil?
      return redirect_to home_url
    end

  	slug = params[:slug]
  	@categories = Category.all()

  	if slug
  		category = Category.find_by slug: slug
	  	if not category
			 render :text => 'Not Found', :status => '404'
	  	else
			 @products = Product.where(category: category).all()
		end
	else
		@products = Product.all()
	end
  end

  def addproduct
    slug = params[:slug]
    product = Product.find_by slug: slug
    if product
      products_ids = session[:products_id]
      if products_ids
        data_ids = products_ids.to_s + ',' + product.id.to_s
      else
        data_ids = product.id.to_s
      end
      session[:products_id] = data_ids
    end
    redirect_to wishlist_url
  end

  def removeproduct
    slug = params[:slug]
    product = Product.find_by slug: slug
    if product
      products_ids = session[:products_id]
      if not products_ids.nil?

        items_ids = products_ids.split(',')
        items_ids.delete(product.id.to_s)
        session[:products_id] = items_ids.join(',')

        if items_ids.count() < 1
          session.delete('products_id')
        end
      end    
    end
    redirect_to wishlist_url
  end

  def wishlist
    user_id = session[:user_id]
    if user_id.nil?
      return redirect_to home_url
    end    
    products_ids = session[:products_id]
    if not products_ids
      return redirect_to catalog_url
    else
      products_ids = session[:products_id].split(',')
      @products = Product.where(id: products_ids)
    end
  end

  def addwishlist
    user_id = session[:user_id]
    if not user_id
      return redirect_to home_url
    end
    user = User.find(user_id)
    if not user
      return redirect_to home_url
    end
    products_ids = session[:products_id]
    if not products_ids
      return redirect_to catalog_url
    end
    products_ids = products_ids.split(',')
    @products = Product.where(id: products_ids)
    friend = Friend.new
    friend.save()
    wishlist = Wishlist.new
    wishlist.user = user
    wishlist.friend = friend
    wishlist.status = 'pending'
    wishlist.save()
    @products.each do |p|
      wishlist_detail = WishlistDetail.new
      wishlist_detail.wishlist = wishlist
      wishlist_detail.product = p
      wishlist_detail.save()
    end
    session['wishlist_id'] = wishlist.id
    redirect_to addfriend_url
  end

  def thanks
  end


  def mywishlist
    session.delete('user_id')
    session.delete('products_id')
    session.delete('wishlist_id')
    wishlist_id = params[:id].to_i
    @wishlist = Wishlist.find_by id: wishlist_id
    if not @wishlist
      render :text => 'Not Found', :status => '404'
    end

    session['mywishlist_id'] = wishlist_id

  end

  def addfriend
    user_id = session[:user_id]
    if user_id.nil?
      return redirect_to home_url
    end
    user = User.find(user_id)
    if not user
      return redirect_to home_url
    end
    wishlist_id = session['wishlist_id']
    if not wishlist_id
      return redirect_to home_url
    end
    wishlist = Wishlist.find(wishlist_id)
    if not wishlist
      return redirect_to home_url
    end

    @url = mywishlist_url(wishlist.id.to_s) + '?fbrefresh=' + rand(100000).to_s
    p 'mywishlist *****************************************************************'
    p @url
    p 'mywishlist *****************************************************************'
    @client_id = App::Application.config.facebook_api_key
  end

end

app/controllers/facebook_controller.rb
#require 'oauth2' 

class FacebookController < ApplicationController

    def index
        client_id = App::Application.config.facebook_api_key
        client_secret = App::Application.config.facebook_api_secret
        authorize_url = App::Application.config.facebook_authorize_url
        redirect_uri = request.original_url
        
        code = params[:code]

        if not code
            url = "#{authorize_url}?client_id=#{client_id}&scope=email&redirect_uri=#{redirect_uri}"
            redirect_to url
        else
            graph_url = App::Application.config.facebook_graph_url
            access_token_url = App::Application.config.facebook_access_token_url

            params = {:params =>{
                :client_id =>client_id,
                :client_secret => client_secret,
                :redirect_uri => redirect_uri,
                :code => code}}

            r = RestClient.get access_token_url, params
            access_token = r.to_s.split("&")[0].split('=')[1]
            expires = r.to_s.split("&")[1].split('=')[1]
            
            url = "#{graph_url}/v2.2/me?access_token=#{access_token}"
            r = RestClient.get url
            data = JSON.parse(r.to_s)
            user = User.find_by fb_id: data['id']

            if not user
                user = User.new
                user.first_name = data['first_name']
                user.last_name = data['last_name']
                user.email = data['email']
                user.fb_id = data['id']
            else
           
                mywishlist_id = session['mywishlist_id']

                if not mywishlist_id.nil?
                    wishlist = Wishlist.find_by id: mywishlist_id
                    if not wishlist.nil?
                        if wishlist.user != user
                            p 'different user'
                            friend = Friend.find_by id: wishlist.friend.id
                            friend.first_name = data['first_name']
                            friend.last_name = data['last_name']
                            friend.fb_id = data['id']

                            p 'try update friend'
                            begin
                                friend.save
                            rescue Exception => e
                                p e
                            end

                            wishlist.status = 'complete'
                            begin
                                wishlist.save
                            rescue Exception => e
                                p e
                            end

                        else
                            p 'same user'
                        end
                    else
                        p 'not exists wishlist'
                    end
                    session.delete('mywishlist_id')
                else
                    p 'not exists session'
                end
            end

            user.fb_oauth_token = access_token
            user.fb_expires = expires
            
            begin
                user.save   
                session[:user_id] = user.id

                redirect_to catalog_url

            rescue Exception => e
                p e
            end

        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/addfriend.html.erb
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="" name="description">
<meta content="" name="author">
  <title>UPCLOVE | Add Friend</title>


<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/font-awesome.min.css">
<link rel="stylesheet" href="css/prettyPhoto.css">
<link rel="stylesheet" href="css/price-range.css">
<link rel="stylesheet" href="css/animate.css">
<link rel="stylesheet" href="css/main.css">
<link rel="stylesheet" href="css/responsive.css">
<!--[if lt IE 9]>
<script src="/js/html5shiv.js"></script>
<script src="/js/respond.min.js"></script>
<![endif]-->
<link href="images/ico/favicon.ico" rel="shortcut icon">
<link href="images/ico/apple-touch-icon-144-precomposed.png" sizes="144x144" rel="apple-touch-icon-precomposed">
<link href="images/ico/apple-touch-icon-114-precomposed.png" sizes="114x114" rel="apple-touch-icon-precomposed">
<link href="images/ico/apple-touch-icon-72-precomposed.png" sizes="72x72" rel="apple-touch-icon-precomposed">
<link href="images/ico/apple-touch-icon-57-precomposed.png" rel="apple-touch-icon-precomposed">
<!--/head-->
</head>
<body>
<header id="header"><!--header--> </header>
<div class="header_top"><!--header_top-->
<div class="container">
<div class="row">
<div class="col-sm-5">
<div class="contactinfo">
<ul class="nav nav-pills">
<li><a href="http://www.falabella.com.pe/falabella-pe/category/cat2190464/?sid=H3842"><img src="logosaga.gif">Saga Falabella</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
<!--/header_top-->
<h1>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; Choose Friend</h1>
<div class="container">
<div class="row">
<div class="col-sm-4">
<div class="signup-form"><!--sign up form-->



<a class="btn btn-success btn-large" href="javascript:add_friend_dialog();"><i class="icon-white icon-heart"></i> Choose Friend</a>



</div>
<!--/sign up form--> </div>
<div class="col-sm-4 col-sm-offset-1">
<div class="login-form"><!--login form-->
<form action="#"> <a href="http://www.falabella.com.pe/falabella-pe/category/cat2190464/?sid=H3842"><img src="armawishlist.jpg"></a> </form>
</div>
<!--/login form--> </div>
</div>
</div>
<!--/form-->&nbsp;<footer id="footer">
</footer>
<div class="footer-bottom">
<div class="container">
<div class="row">
<p class="pull-left">Copyright © 2015 IngenioWeb Inc. All
rights reserved.</p>
<p class="pull-right">Designed by IngenioWeb</p>
</div>
</div>
</div>
<!--/Footer-->

 <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '<%= @client_id %>',
        xfbml      : true,
        version    : 'v2.1'
        });
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));

    function add_friend_dialog()
    {
      
      /*
      FB.ui({
        method: 'send',
        link: '<%= @url  %>',
      }, function(x){
          if (x!=null){
            window.location = '<%= thanks_url  %>';
          }
      });
    }
*/
    



      FB.api('https://graph.facebook.com/', 'post', {
          id: '<%= @url  %>',
          scrape: true
      }, function(response) {
        console.log(response)
          FB.ui({
              method: 'send',
              link: '<%= @url  %>'
          }, function(x){
            console.log(x)
          if (x!=null){
            window.location = '<%= thanks_url  %>';
          }
      });
      });

 }

  </script>


<script src="/js/jquery.js"></script>
<script src="/js/price-range.js"></script>
<script src="/js/jquery.scrollUp.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.prettyPhoto.js"></script>
<script src="/js/main.js"></script>
</body></html>

app/views/application/catalog.html.erb
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
	<title>UPCLOVE | Catalog</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <link href="/css/prettyPhoto.css" rel="stylesheet">
    <link href="/css/price-range.css" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
	<link href="/css/main.css" rel="stylesheet">
	<link href="/css/responsive.css" rel="stylesheet"><!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <script src="/js/respond.min.js"></script>
    <![endif]-->
           
    <link rel="shortcut icon" href="/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/images/ico/apple-touch-icon-57-precomposed.png"><!--/head--></head>
<body>
	<header id="header"><!--header-->
		</header><div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@ingenioweb.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="https://www.facebook.com/sagafalabella?fref=ts"><i class="fa fa-facebook"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							Catálogo de Productos
						</div>

					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<!--/header-bottom-->
	<!--/header-->
		
	<section>
		</section><div class="container">
			<div class="row">
			
		
					<div class="category-tab"><!--category-tab-->
						<div style="text-align: right;" class="col-sm-12">
							<ul class="nav nav-tabs">



		<% @categories.each do |p| %>
		<li><a href="<%= catalog_url(slug:p.slug) %>"><%= p.name %></a></li>
		<% end %>
<!--		
								<li class="active"><a href="#Ropa" data-toggle="tab">Ropa</a></li>
								<li><a href="#Peluche" data-toggle="tab">Peluche</a></li>
								<li><a href="#Calzado" data-toggle="tab">Calzado</a></li>
								<li><a href="#Perfumes" data-toggle="tab">Perfumes</a></li>
								<li><a href="#poloshirt" data-toggle="tab">Polo shirt</a></li> -->
							</ul>
						</div>





						<div class="tab-content">
							<div class="tab-pane fade active in" id="Ropa">


					<% @products.each.with_index do |p, index| %>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center"><div style="text-align: center;">
												<img src="/<%= p.photo_path %>" alt="">
												</div><h2>$56</h2>
												<p><%= p.title %></p>
												<a href="<%= addproduct_url(slug:p.slug) %>">Add Wishlist</a>
											</div>
											
										</div>
									</div>
								</div>
							<% end %>
							</div>
						</div>


					</div><!--/category-tab-->
					
	
					
				</div>
			</div>
		
		<div class="common-modal modal fade" id="common-Modal1" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-content">
				<ul class="list-inline item-details">
					<li><a href="http://themifycloud.com">ThemifyCloud</a></li>
					<li><a href="http://themescloud.org">ThemesCloud</a></li>
				</ul>
			</div>
		</div>
	
	
	<footer id="footer"><!--Footer-->
		</footer><div class="footer-top">
			
		
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2015 IngenioWeb Inc. All
rights reserved.</p>
					<p class="pull-right">Designed by IngenioWeb</p>
				</div>
			</div>
		</div>
		
	<!--/Footer-->
	

  
    <script src="/js/jquery.js"></script>
	<script src="/js/bootstrap.min.js"></script>
	<script src="/js/jquery.scrollUp.min.js"></script>
	<script src="/js/price-range.js"></script>
    <script src="/js/jquery.prettyPhoto.js"></script>
    <script src="/js/main.js"></script>
</div></body></html>

app/views/application/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
	<title>UPCLOVE | Home</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/price-range.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
	<link href="css/main.css" rel="stylesheet">
	<link href="css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <script src="/js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->


<body>

	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="http://www.falabella.com.pe/falabella-pe/category/cat2190464/?sid=H3842"><img src="logosaga.gif">Saga Falabella</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="https://es-la.facebook.com/sagafalabella"><i class="fa fa-facebook"></i></a></li>
								<li><a href="https://twitter.com/saga_falabella"><i class="fa fa-twitter"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
	</header><!--/header-->
	
	<section id="form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<div class="signup-form"><!--sign up form-->
						<h1>TU MEJOR REGALO</h1>
						
						<h4>Genera tu wishlist y enviaselo a un amigo para que revise tu regalo deseado<h4>
						<form action="<%= facebook_path  %>">
						<button type="submit" class="btn btn-default">Login with Facebook</button>
						</form>
					</div><!--/sign up form-->
				</div>
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<form action="#">
							<a href="http://www.falabella.com.pe/falabella-pe/category/cat2190464/?sid=H3842"><img src="armawishlist.jpg"></a>
						</form>
					</div><!--/login form-->
				</div>
			</div>
		</div>
	</section><!--/form-->
	
	
	<footer id="footer"><!--Footer-->
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2015 IngenioWeb Inc. All rights reserved.</p>
					<p class="pull-right">Designed by IngenioWeb</p>
				</div>
			</div>
		</div>
	</footer><!--/Footer-->
    <script src="/js/jquery.js"></script>
	<script src="/js/price-range.js"></script>
    <script src="/js/jquery.scrollUp.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.prettyPhoto.js"></script>
    <script src="/js/main.js"></script>
</body>
</html>

app/views/application/wishlist.html.erb
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>UPCLOVE | WishList</title>
<link href="/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/font-awesome.min.css" rel="stylesheet">
<link href="/css/prettyPhoto.css" rel="stylesheet">
<link href="/css/price-range.css" rel="stylesheet">
<link href="/css/animate.css" rel="stylesheet">
<link href="/css/main.css" rel="stylesheet">
<link href="/css/responsive.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<script src="js/respond.min.js"></script>
<![endif]-->
<link rel="shortcut icon" href="/images/ico/favicon.ico">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/images/ico/apple-touch-icon-57-precomposed.png">
<!--/head-->
</head>



<body>
<header id="header"><!--header--> </header>
<div class="header_top"><!--header_top-->
<div class="container">
<div class="row">
<div class="col-sm-5">
<div class="contactinfo">
<ul class="nav nav-pills">
<li><a href="http://www.falabella.com.pe/falabella-pe/category/cat2190464/?sid=H3842"><img src="logosaga.gif">Saga Falabella</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
<!--/header_top-->
<h1>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; WishList</h1>
<div class="container">
<div class="row">
<div class="col-sm-4">
<div class="signup-form"><!--sign up form-->

<form method="post" action="<%= addwishlist_path  %>">
<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>




<div class="tab-content">
	<div class="tab-pane fade active in" id="Ropa">
	<% @products.each.with_index do |p, index| %>
		<div class="col-sm-5">
			<div class="product-image-wrapper">
				<div class="single-products">
					<div class="productinfo text-center"><div style="text-align: center;">
						<img src="/<%= p.photo_path %>" alt="">
						</div><h2>$56</h2>
						<p><%= p.title %></p>
						<a href="<%= removeproduct_url(slug:p.slug) %>">Remove</a>
					</div>
					
				</div>
			</div>
		</div>
	<% end %>
	</div>
</div>

<input type="submit">
</form>

</div>
<!--/sign up form--> </div>
<div class="col-sm-4 col-sm-offset-1">
<div class="login-form"><!--login form-->
<form action="#"> <a href="http://www.falabella.com.pe/falabella-pe/category/cat2190464/?sid=H3842"><img src="armawishlist.jpg"></a> 
<br />
<br />

<a href="<%= catalog_url %>">Back to Catalog</a>
</form>
</div>
<!--/login form--> </div>
</div>
</div>
<!--/form-->&nbsp;<footer id="footer">
</footer>
<div class="footer-bottom">
<div class="container">
<div class="row">
<p class="pull-left">Copyright © 2015 IngenioWeb Inc. All
rights reserved.</p>
<p class="pull-right">Designed by IngenioWeb</p>
</div>
</div>
</div>
<!--/Footer-->
<script src="js/jquery.js"></script>
<script src="js/price-range.js"></script>
<script src="js/jquery.scrollUp.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.prettyPhoto.js"></script>
<script src="js/main.js"></script>
</body></html>

app/views/layouts/application.html.erb
<%= yield %>